### ISSUE TITLE
Auto-type over BT doesnt work

### ISSUE THREAD

**Issue by ghost** [tejado/Authorizer#34]
Lineage OS 17.1(based on AOSP 10)

Logs:
```
08-03 20:48:05.088 19118 19118 D BluetoothHidDevice: Binding service...
08-03 20:48:05.089 19118 19118 E BluetoothHidDevice: Could not bind to Bluetooth Service with Intent { act=android.bluetooth.IBluetoothHidDevice }
08-03 20:48:06.113 19118 19118 E InputEventReceiver: Exception dispatching input event.
08-03 20:48:06.113 19118 19118 E MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.bluetooth.BluetoothHidDevice.getConnectionState(android.bluetooth.BluetoothDevice)' on a null object reference
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at net.tjado.authorizer.OutputBluetoothKeyboard.connectDeviceAndSend(OutputBluetoothKeyboard.java:283)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at net.tjado.passwdsafe.PasswdSafeRecordBasicFragment$26.onClick(PasswdSafeRecordBasicFragment.java:935)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1222)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.widget.AdapterView.performItemClick(AdapterView.java:330)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.widget.AbsListView.performItemClick(AbsListView.java:1190)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.widget.AbsListView$PerformClick.run(AbsListView.java:3198)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.widget.AbsListView.onTouchUp(AbsListView.java:4128)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.widget.AbsListView.onTouchEvent(AbsListView.java:3886)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.view.View.dispatchTouchEvent(View.java:13953)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3054)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2741)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:465)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1849)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.app.Dialog.dispatchTouchEvent(Dialog.java:861)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:423)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.view.View.dispatchPointerEvent(View.java:14212)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5652)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5455)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5117)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4985)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5174)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4985)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7675)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7644)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7605)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7800)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:188)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.os.MessageQueue.nativePollOnce(Native Method)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.os.MessageQueue.next(MessageQueue.java:336)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.os.Looper.loop(Looper.java:174)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at android.app.ActivityThread.main(ActivityThread.java:7356)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at java.lang.reflect.Method.invoke(Native Method)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
08-03 20:48:06.114 19118 19118 E MessageQueue-JNI:      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
08-03 20:48:06.114 19118 19118 D AndroidRuntime: Shutting down VM
08-03 20:48:06.115 19118 19118 E AndroidRuntime: FATAL EXCEPTION: main
08-03 20:48:06.115 19118 19118 E AndroidRuntime: Process: net.tjado.passwdsafe, PID: 19118
08-03 20:48:06.115 19118 19118 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.bluetooth.BluetoothHidDevice.getConnectionState(android.bluetooth.BluetoothDevice)' on a null object reference
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at net.tjado.authorizer.OutputBluetoothKeyboard.connectDeviceAndSend(OutputBluetoothKeyboard.java:283)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at net.tjado.passwdsafe.PasswdSafeRecordBasicFragment$26.onClick(PasswdSafeRecordBasicFragment.java:935)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1222)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.widget.AdapterView.performItemClick(AdapterView.java:330)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.widget.AbsListView.performItemClick(AbsListView.java:1190)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3198)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.widget.AbsListView.onTouchUp(AbsListView.java:4128)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.widget.AbsListView.onTouchEvent(AbsListView.java:3886)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.view.View.dispatchTouchEvent(View.java:13953)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3054)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2741)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:465)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1849)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.app.Dialog.dispatchTouchEvent(Dialog.java:861)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:423)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.view.View.dispatchPointerEvent(View.java:14212)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5652)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5455)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5117)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4985)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5174)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4985)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7675)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7644)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7605)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7800)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:188)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.os.MessageQueue.nativePollOnce(Native Method)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.os.MessageQueue.next(MessageQueue.java:336)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:174)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
08-03 20:48:06.115 19118 19118 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
08-03 20:48:06.118  1552  5270 W ActivityTaskManager:   Force finishing activity net.tjado.passwdsafe/.PasswdSafe
```

**Comment by tejado** [comment]
Thanks. The Bluetooth functionality is not working very well (at least for me) so I prefer USB. But I will look into it.

**Comment by tejado** [comment]
In #48 the bluetooth feature was implemented in a more stable way. Please check.
