### ISSUE TITLE
Bluetooth failure on Android 13

### ISSUE THREAD

**Issue by gh-gmn** [tejado/Authorizer#44]
An android 13 I get the following error in logcat:
```
10-20 10:52:15.362 16583 16583 E AndroidRuntime: Process: net.tjado.passwdsafe, PID: 16583
10-20 10:52:15.362 16583 16583 E AndroidRuntime: java.lang.SecurityException: Need BLUETOOTH permission
10-20 10:52:15.362 16583 16583 E AndroidRuntime:  at android.bluetooth.BluetoothProfileConnector.connect(BluetoothProfileConnector.java:177)
10-20 10:52:15.362 16583 16583 E AndroidRuntime:  at android.bluetooth.BluetoothHidDevice.<init>(BluetoothHidDevice.java:445)
10-20 10:52:15.362 16583 16583 E AndroidRuntime:  at android.bluetooth.BluetoothAdapter.getProfileProxy(BluetoothAdapter.java:3645)
10-20 10:52:15.362 16583 16583 E AndroidRuntime:  at net.tjado.authorizer.OutputBluetoothKeyboard.initializeBluetoothHidDevice(OutputBluetoothKeyboard.java:187)
```
I don't think it needs that permission on Android 13 and I see that in the source, however perhaps it's based on the target sdk rather than the device level.

**Comment by tejado** [comment]
Thank you for reporting it. As the permissions changed in recent Android versions, Authorizer has to be made compatible to them. I will have a look on it.

**Comment by tejado** [comment]
PR #48 made a lot of improvements including to bluetooth - please check.
